---
 - name: playbook1
   hosts: all
   tasks:
     - name: check the date
       command: date
     - name: installation of webserver 
       yum:
        name: httpd
        state: present
     - name: start the webserver
       service:
         name: httpd
         state: started
     - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
     - name: installation of java
       yum:
        name: java
        state: present
